FROM node:18-alpine AS build
WORKDIR /my-texas-42-frontend
COPY package.json yarn.lock ./
RUN yarn cache clean
RUN yarn install
COPY . .
ENV CI=true
ARG REACT_APP_ENVIRONMENT
ARG REACT_APP_DEV_API_PATH
ARG REACT_APP_STAGING_API_PATH
ARG REACT_APP_PRODUCTION_API_PATH
ARG REACT_APP_DEV_WEBSOCKET_API_PATH
ARG REACT_APP_STAGING_WEBSOCKET_API_PATH
ARG REACT_APP_PRODUCTION_WEBSOCKET_API_PATH
ENV REACT_APP_ENVIRONMENT=$REACT_APP_ENVIRONMENT
ENV REACT_APP_DEV_API_PATH=$REACT_APP_DEV_API_PATH
ENV REACT_APP_STAGING_API_PATH=$REACT_APP_STAGING_API_PATH
ENV REACT_APP_PRODUCTION_API_PATH=$REACT_APP_PRODUCTION_API_PATH
ENV REACT_APP_DEV_WEBSOCKET_API_PATH=$REACT_APP_DEV_WEBSOCKET_API_PATH
ENV REACT_APP_STAGING_WEBSOCKET_API_PATH=$REACT_APP_STAGING_WEBSOCKET_API_PATH
ENV REACT_APP_PRODUCTION_WEBSOCKET_API_PATH=$REACT_APP_PRODUCTION_WEBSOCKET_API_PATH
RUN yarn build

FROM nginx:alpine
COPY --from=build /my-texas-42-frontend/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
